version: '3'
services:
  # setup node server container
  server:
    build: ./server
    restart: always
    expose:
      - 8000
    environment: 
      API_HOST: http://localhost:8096/
      APP_SERVER_PORT: 8000
    ports: 
      - "49160:8000"
    volumes: 
      - ./server:/server/app
      #- filemanager-data:/server/app/public/files
      # - ./client/public/files:/client/public/files
      - /content/filemanager_data/:/server/app/public/files
      - /server/app/node_modules
      - .:/server/app
    command: nodemon server.js

#  set up client container
  client:
    build: ./client
    environment: 
      - REACT_APP_PORT=8096
    expose: 
      - 8096
    ports:
      - "8096:80"
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
      # - filemanager-data:/usr/share/nginx/html/files
      - /content/filemanager_data/:/usr/share/nginx/html/files
      - /app/node_modules
      - .:/app
    links:
      - server
      #- elasticDoc
    # command: npm run start #or start
volumes:
  filemanager-data:
    external: false


#  web:
#   build:
#    context: .
#    dockerfile: Dockerfile
#   ports:
#    - "3000:80"
#    - "49160:8000"
#   volumes:
#    - /app/node_modules
#    - .:/app
