version: '3'
services:
  # setup node server container
  server:
    build: ./server
    expose:
      - 8000
    environment: 
      API_HOST: http://localhost:3000/
      APP_SERVER_PORT: 8000
    ports: 
      - "49160:8000"
    volumes: 
      - ./server:/server/app
      - filemanager-data:/server/app/public/files
      # - ./client/public/files:/client/public/files
      - /server/app/node_modules
      - .:/server/app
    command: nodemon server.js

#  set up client container
  client:
    build: ./client
    environment: 
      - REACT_APP_PORT=3000
    expose: 
      - 3000
    ports:
      - "3000:80"
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
      - filemanager-data:/usr/share/nginx/html/files
      - /app/node_modules
      - .:/app
    links:
      - server
    # command: npm run start #or start
volumes:
  filemanager-data:
    external: false


#  web:
#   build:
#    context: .
#    dockerfile: Dockerfile
#   ports:
#    - "3000:80"
#    - "49160:8000"
#   volumes:
#    - /app/node_modules
#    - .:/app
