export const ADD_DOCUMENNT = "ADD_DOCUMENT";
export const FETCH_DOCUMENT = "FETCH_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const FETCH_ALL_DOCUMENTS = "FETCH_ALL_DOCUMENTS";

export const FETCH_LATESTS = "FETCH_LATESTS";